#Don't change this line!
version: 1
#=================================
#Network Settings

#The prefix the message system will use when sending messages. 
#Only servers with matching prefixes will recieve messages from this server.
channel-prefix: 'network'

#=================================
#Information Settings

name: 'New Server'
description: ''
categories: []

#=================================
#Hub Control Settings

hub-enabled: false

#=================================
#Advanced Settings

hub-priority: 0
hub-conflict-resolver: RANDOM

#The amount of time, in ms, to wait for responses from servers.
#If a server fails to respond, a command involving requests might take as long as the timeout.
request-timeout: 500

#Whether to show debug messages or not. 1 = enabled, 2 = verbose
debug-messages: 0

#=================================

connection-attempts-max: 10
connection-attempts-interval: 1000