#=================================
#Don't change this line!
version: 0
#=================================

#The amount of time, in ms, to wait for responses from servers.
#If a server fails to respond, a command involving requests might take as long as the timeout.
request-timeout: 500

#Whether to show debug messages or not. 1 = enabled, 2 = verbose
debug-messages: 0

#The prefix the message system will use when sending messages. 
#Only servers with matching prefixes will recieve messages from this server.
channel-prefix: 'network'

use-as-hub: false
#The priority of the hub. The hub order goes from low to high. 
#Don't use duplicate priorities for different servers. 
hub-priority: 0

#=================================

lilypad-connection-attempts-max: 10
lilypad-connection-attempts-wait: 1000