name: Universe
main: com.hyperfresh.mc-universe.BukkitUniversePlugin
version: ${version}
softdepend: ['LilyPad-Connect']
permissions:
    universe.server.connect:
        default: true
    universe.server.list:
        default: true
    universe.main:
        default: true
